
name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - Develop-BE

jobs:
  build-tocktock:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application.properties
        run: |
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties
        shell: bash

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tocktock
          path: build/libs/*.jar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t tocktock:${{ github.sha }} .
          docker tag tocktock:${{ github.sha }} ${{ secrets.DOCKER_NAME }}/tocktock:latest
          docker push ${{ secrets.DOCKER_NAME }}/tocktock:latest

      - name: Docker Setting
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          port: ${{ secrets.ORACLE_PORT }}
          script: |
            docker stop tocktock || true
            docker rm tocktock || true
            docker rmi ${{ secrets.DOCKER_NAME }}/tocktock:latest || true
            docker pull ${{ secrets.DOCKER_NAME }}/tocktock:latest
            docker run -d -p 8080:8080 --name tocktock ${{ secrets.DOCKER_NAME }}/tocktock:latest